# Generated by Django 6.0.6 on 2026-06-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='max_retries',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed'), ('dead', 'Dead')], default='pending', max_length=20),
        ),
    ]
